version: "3.9"
services:
  dpsim:
    image: sogno/dpsim:dev
    environment:
      PYTHONPATH: /dpsim/build
    ports:
      - "8888:8888"
    volumes:
      - ../../..:/dpsim
    privileged: true
    stdin_open: true
    tty: true
  mqtt:
    image: eclipse-mosquitto:latest
    hostname: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    stdin_open: true
    tty: true
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
