name: Build & Test Fedora Minimal

on: push

## Build ##

jobs:
  linux-fedora-minimal:
    name: Build with minimal configuration on Fedora Linux
    runs-on: ubuntu-latest
    container: sogno/dpsim:dev-minimal
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create Build Environment
      run: mkdir build

    - name: Configure CMake
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake -DWITH_SPDLOG_SUBMODULE=ON $GITHUB_WORKSPACE

    - name: Build every target
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake --build .
      env:
        MAKEFLAGS: "-j2"

    - name: Cache build directory
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/build
        key: build-cache-fedora-minimal-${{ github.sha }}
## Tests ##
  #TODO