name: Generate

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    container: sogno/dpsim:dev
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create Build Environment
      run: mkdir build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE

    - name: Generate docs
      run: |
        make -j$(nproc) -C build docs
        make -j$(nproc) -C build docs_cxx

    - name: Copy docs
      run: |
        cp -r build/docs/sphinx/html/. public/sphinx
        cp -r build/docs/doxygen/html/. public/doxygen

    - name: Deploy page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}     
        publish_dir: ./public
        #   keep_files: true
        publish_branch: gh-pages